Simulationproducts/config/routes.rb
Rails.application.routes.draw do
  
  resources :buyers
  resources :productos
  resources :promociones
  resources :reportes_de_ventas
  resources :productos_types

  root 'productos#index'

  resources :buyers do
    member do
      get :inactivar
      post :suscribir
    end

  collection do
    get :search
  end

  resources :promociones
  end

  namespace :admin do
    resources :productos
  end

  scope '/admin' do
    resources :reportes_de_ventas
  end

end

Simulationproducts/app/models/buyer.rb
class Buyer < ActiveRecord::Base
end

Simulationproducts/app/models/producto.rb
class Producto < ActiveRecord::Base

validates :marca, :talla, :referencia, :color, :stock, :descripcion, :costo, :preciodeventa, presence: true
validates :marca, inclusion: {in: %w(Adidas Nike Reebok LaCoste Americanino Chevignon Edc Gef Stop Jeans), message: "%{value} No es una marca valida"}
validates :talla, inclusion: {in: %w(S M L XL XXl), message: "%{value} No es una talla valida"}
validates :referencia, length: { is:5 }
validates :stock, numericality: {only_integer: true}
validates :color, exclusion: {in: %w(Amarillo Verde Anaranjado), message: "%{value} Color no esta disponible"}
validates :descripcion, length: {maximum: 100}
validates :costo, :preciodeventa, numericality: {greater_than: 0}

end

Simulationproducts/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Simulationproducts/app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  before_action :set_buyer, only: [:show, :edit, :update, :destroy]

  # GET /buyers
  # GET /buyers.json
  def index
    @buyers = Buyer.all
  end

  # GET /buyers/1
  # GET /buyers/1.json
  def show
  end

  # GET /buyers/new
  def new
    @buyer = Buyer.new
  end

  # GET /buyers/1/edit
  def edit
  end

  # POST /buyers
  # POST /buyers.json
  def create
    @buyer = Buyer.new(buyer_params)

    respond_to do |format|
      if @buyer.save
        format.html { redirect_to @buyer, notice: 'Buyer was successfully created.' }
        format.json { render :show, status: :created, location: @buyer }
      else
        format.html { render :new }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buyers/1
  # PATCH/PUT /buyers/1.json
  def update
    respond_to do |format|
      if @buyer.update(buyer_params)
        format.html { redirect_to @buyer, notice: 'Buyer was successfully updated.' }
        format.json { render :show, status: :ok, location: @buyer }
      else
        format.html { render :edit }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buyers/1
  # DELETE /buyers/1.json
  def destroy
    @buyer.destroy
    respond_to do |format|
      format.html { redirect_to buyers_url, notice: 'Buyer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buyer
      @buyer = Buyer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buyer_params
      params.require(:buyer).permit(:name, :lastname, :identification, :edad, :profesion)
    end
end

Simulationproducts/app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all
    @productos = Producto.order(:marca)
    #@productos = Producto.find(10)
    #@productos = Producto.take(10)
    #@productos = Producto.first
    #@productos = Producto.last
    #@productos = Producto.find_by_color("blanco")
    #@productos = Producto.where(talla: ["s", "l"])
    #@productos = Producto.where.not(talla: ["s", "l"])
    #@productos = Producto.where.not(talla: ["s", "l"])
    #@productos = Producto.order(precio: :desc)
    #@productos = Producto.select(:costo, :precio)
    #@productos = Producto.limit(5).offset(10)
    #@productos = Producto.limit(5).offset(10)
    #@productos = Producto.group(:talla)
    #@productos = Producto.group(:tipo).having("sum(precio) > ?", 2800000)
    #@productos = Producto.all.readonly
    #@productos = Producto.includes(:categoria).limit(10)
    #@productos = Producto.where("cantidad > ? AND tipo = ?", 100, "hombre")
    @productos = Producto.where("referencia like  ? ", "%#{params[:referencia]}%")
    @productos = Producto.where("tipo_producto like  ? ", "%#{params[:tipo_producto]}%")
    #pluck, sum, minimum, maximum, average
    @total_stock = Producto.sum(:stock)
    @maximo_costo = Producto.maximum(:costo)
    @promedio_ventas = Producto.average(:preciodeventa)

  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:referencia, :marca, :talla, :tipo_producto, :color, :categoria, :stock, :tela, :descripcion, :costo, :preciodeventa)
    end
end

Simulationproducts/app/helpers/application_helper.rb
module ApplicationHelper
end

Simulationproducts/app/helpers/buyers_helper.rb
module BuyersHelper
end

Simulationproducts/app/helpers/comprador_helper.rb
module CompradorHelper
end

Simulationproducts/app/helpers/productos_helper.rb
module ProductosHelper
end

Simulationproducts/app/views/buyers/_form.html.erb
<%= form_for(@buyer) do |f| %>
  <% if @buyer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@buyer.errors.count, "error") %> prohibited this buyer from being saved:</h2>

      <ul>
      <% @buyer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :identification %><br>
    <%= f.text_field :identification %>
  </div>
  <div class="field">
    <%= f.label :edad %><br>
    <%= f.number_field :edad %>
  </div>
  <div class="field">
    <%= f.label :profesion %><br>
    <%= f.text_field :profesion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Simulationproducts/app/views/buyers/edit.html.erb
<h1>Editing Buyer</h1>

<%= render 'form' %>

<%= link_to 'Show', @buyer %> |
<%= link_to 'Back', buyers_path %>

Simulationproducts/app/views/buyers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Buyers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Lastname</th>
      <th>Identification</th>
      <th>Edad</th>
      <th>Profesion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buyers.each do |buyer| %>
      <tr>
        <td><%= buyer.name %></td>
        <td><%= buyer.lastname %></td>
        <td><%= buyer.identification %></td>
        <td><%= buyer.edad %></td>
        <td><%= buyer.profesion %></td>
        <td><%= link_to 'Show', buyer %></td>
        <td><%= link_to 'Edit', edit_buyer_path(buyer) %></td>
        <td><%= link_to 'Destroy', buyer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Buyer', new_buyer_path %>

Simulationproducts/app/views/buyers/new.html.erb
<h1>New Buyer</h1>

<%= render 'form' %>

<%= link_to 'Back', buyers_path %>

Simulationproducts/app/views/buyers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @buyer.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @buyer.lastname %>
</p>

<p>
  <strong>Identification:</strong>
  <%= @buyer.identification %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @buyer.edad %>
</p>

<p>
  <strong>Profesion:</strong>
  <%= @buyer.profesion %>
</p>

<%= link_to 'Edit', edit_buyer_path(@buyer) %> |
<%= link_to 'Back', buyers_path %>

Simulationproducts/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simulationproducts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Simulationproducts/app/views/productos/_form.html.erb
<%= form_for(@producto) do |f| %>
  <% if @producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% @producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= f.label :referencia %><br>
    <%= f.text_field :referencia %>
  </div>
  <div class="field">
    <%= f.label :marca %><br>
    <%= f.text_field :marca %>
  </div>
  <div class="field">
    <%= f.label :talla %><br>
    <%= f.text_field :talla %>
  </div>
  <div class="field">
    <%= f.label :tipo_producto%><br>
    <%= f.text_field :tipo_producto %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :categoria %><br>
    <%= f.text_field :categoria %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="field">
    <%= f.label :tela %><br>
    <%= f.text_field :tela%>
  </div>

    <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :costo %><br>
    <%= f.text_field :costo %>
  </div>
  <div class="field">
    <%= f.label :preciodeventa %><br>
    <%= f.text_field :preciodeventa %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Simulationproducts/app/views/productos/edit.html.erb
<h1>Editing Producto</h1>

<%= render 'form' %>

<%= link_to 'Show', @producto %> |
<%= link_to 'Back', productos_path %>

Simulationproducts/app/views/productos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Productos</h1>

<h2>Buscar referencia:</h2>
  <%= form_tag "/productos", method: :get do |f| %>
  <%= label_tag "Referencia" %>
  <%= text_field_tag :referencia %><span class="button"><%= submit_tag "Buscar" %></span>
  
  <% end%>

<h2>Tipo de producto:</h2>
  <%= form_tag "/productos", method: :get do |f| %>
  <%= label_tag "Digite tipo de producto" %>
  <%= text_field_tag :tipo_producto %> <span class="button"><%= submit_tag "Buscar" %></span>
   
  <% end%>

<table>
  <thead>
    <tr>
      <th>Referencia</th>
      <th>Marca</th>
      <th>Talla</th>
      <th>Tipo de producto</th>
      <th>Color</th>
      <th>Categoria</th>
      <th>Stock</th>
      <th>Tela</th>
      <th>Descripcion</th>
      <th>Costo</th>
      <th>Precio de venta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= producto.referencia %></td>
        <td><%= producto.marca %></td>
        <td><%= producto.talla %></td>
        <td><%= producto.tipo_producto %></td>
        <td><%= producto.color %></td>
        <td><%= producto.categoria %></td>
        <td><%= producto.stock %></td>
        <td><%= producto.tela %></td>
        <td><%= producto.descripcion %></td>
        <td><%= producto.costo %></td>
        <td><%= producto.preciodeventa %></td>
        <td><%= link_to 'Show', producto %></td>
        <td><%= link_to 'Edit', edit_producto_path(producto) %></td>
        <td><%= link_to 'Destroy', producto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<h2>Stock actual bodega:</h2> <span><%= @total_stock %></span>

<h2>Promedio de venta de productos:</h2><span><%= @promedio_ventas%></span>



<br>

<%= link_to 'Nuevo producto', new_producto_path %>

Simulationproducts/app/views/productos/new.html.erb
<h1>New Producto</h1>

<%= render 'form' %>

<%= link_to 'Back', productos_path %>

Simulationproducts/app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Referencia:</strong>
  <%= @producto.referencia %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @producto.marca %>
</p>

<p>
  <strong>Talla:</strong>
  <%= @producto.talla %>
</p>

<p>
  <strong>Tipo de producto:</strong>
  <%= @producto.tipo_producto %>
</p>


<p>
  <strong>Color:</strong>
  <%= @producto.color %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @producto.categoria %>
</p>



<p>
  <strong>Stock:</strong>
  <%= @producto.stock %>
</p>


<p>
  <strong>Tela:</strong>
  <%= @producto.tela %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @producto.descripcion %>
</p>

<p>
  <strong>Costo:</strong>
  <%= @producto.costo %>
</p>

<p>
  <strong>Precio de venta:</strong>
  <%= @producto.preciodeventa %>
</p>

<%= link_to 'Edit', edit_producto_path(@producto) %> |
<%= link_to 'Back', productos_path %>